#!/bin/bash
# One-click Deployment Script for Expense Manager

echo "🚀 Starting One-Click Deployment..."

# 1. Update system & install dependencies
echo "📦 Installing Docker and Git..."
if [ -f /etc/amazon-linux-release ]; then
    sudo yum update -y
    sudo yum install docker git -y
    sudo service docker start
    sudo usermod -a -G docker $USER
elif [ -f /etc/lsb-release ]; then
    sudo apt-get update -y
    sudo apt-get install docker.io git curl -y
    sudo systemctl start docker
    sudo usermod -a -G docker $USER
fi

# 2. Install Docker Compose
echo "🐳 Installing Docker Compose..."
sudo mkdir -p /usr/local/lib/docker/cli-plugins/
sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

# 3. Setup Project Directory
echo "📂 Setting up project..."
cd ~
if [ ! -d "expense" ]; then
    git clone https://github.com/Varunpmv/expense.git
fi
cd expense

# Pull latest changes if it already exists
git pull origin main

# 4. Generate secure .env file if it doesn't exist
if [ ! -f ".env" ]; then
    echo "🔐 Generating secure environment variables..."
    # Generate random passwords
    DB_PASS=$(openssl rand -hex 16)
    AUTH_SECRET=$(openssl rand -hex 32)
    
    # Try to get the public IP of the EC2 instance
    PUBLIC_IP=$(curl -s http://checkip.amazonaws.com || echo "localhost")
    
    cat <<EOF > .env
# Auto-generated by deploy.sh
MYSQL_ROOT_PASSWORD=${DB_PASS}_root
MYSQL_DATABASE=expense_db
MYSQL_USER=expense_user
MYSQL_PASSWORD=${DB_PASS}

DATABASE_URL=mysql://expense_user:${DB_PASS}@db:3306/expense_db
NEXTAUTH_SECRET=${AUTH_SECRET}
NEXTAUTH_URL=http://${PUBLIC_IP}:3000
EOF
    echo "✅ .env file created successfully with secure random passwords."
fi

# 5. Build and Start
echo "🏗️ Building and starting the application..."
# Run docker compose using 'sg' to apply the new docker group without logging out
sg docker -c "docker compose up -d --build"

echo ""
echo "=========================================================="
echo "🎉 DEPLOYMENT COMPLETE! 🎉"
PUBLIC_IP=$(curl -s http://checkip.amazonaws.com || echo "localhost")
echo "Your Expense Manager is running at: http://${PUBLIC_IP}:3000"
echo ""
echo "⚠️ IMPORTANT: Ensure Port 3000 is open in your AWS EC2 Security Group."
echo "=========================================================="
